name: info_x
version: 0.4.4-nullsafety.1
homepage: https://github.com/ericmartineau/info_x
description: A new Flutter package project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  timezone: ^0.7.0-nullsafety.0
  dartxx: ^0.4.5-nullsafety.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
